name: myeg_flutter_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  go_router: ^14.8.1
  http: ^1.3.0
  photo_view: ^0.15.0
  riverpod: ^2.6.1
  riverpod_lint: ^2.6.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
